// Board geometry for the renderer and UI. Generated by `npm run build:map` (scripts/build-map.ts);
// checked by `npm run verify:map`. Coordinates: board units, origin bottom-left, +x east, +y north.

import type { TerritoryId } from '../engine/types';
import type { BoardGeometry, SeaLaneGeom, Vec2 } from './types';
import boardJson from './board.json';

export type * from './types';

export const BOARD: BoardGeometry = boardJson as unknown as BoardGeometry;

/** Where the army piece + count badge sits (inside the main polygon, ≥ 1.3 units from its edge). */
export function territoryAnchor(t: TerritoryId): Vec2 {
  return BOARD.territories[t].anchor;
}

/** Guaranteed free radius around `territoryAnchor` inside the tile (board units). */
export const ANCHOR_CLEARANCE = 1.3;

const laneIndex = new Map<string, SeaLaneGeom>();
for (const lane of BOARD.seaLanes) {
  laneIndex.set(`${lane.a}|${lane.b}`, lane);
  laneIndex.set(`${lane.b}|${lane.a}`, lane);
}

/** The sea lane joining two territories, if their border is a sea crossing (null for land borders). */
export function seaLaneBetween(a: TerritoryId, b: TerritoryId): SeaLaneGeom | null {
  return laneIndex.get(`${a}|${b}`) ?? null;
}
